### ISSUE TITLE
Create Image sets

### ISSUE THREAD

**Issue by Dee-McG** [Dee-McG/Hackathon-Project#56]
**Task**

Create image sets for each scenario using image generator AI for consumption by the application

**Acceptance Criteria**

- Image sets created
- Image sets added to each scene

**Comment by Mrst12** [comment]
Ive put images in the assets and added them to the js file for random selection as wasnt sure how to get them displayed for each scene on its own for my island story

**Comment by Dee-McG** [comment]
Okay did a bit of restructuring, I have just added all images to the scenes that were in the js file but you can now add scenes per story in the json file if you want to update the images in there, should just be a case of uploading them + adding the link to the image in there
